import { health } from './controller/health';
import { logs } from './controller/logs';
import {
    getAgentClaims,
    getPlanetClaims,
    getPlanetDemographics,
    getPlanetDemographicsFull,
    getPlanetEconomy,
    getPlanetMarket,
    getPlanetMarketOverview,
    getPlanetOverview,
} from './controller/planet';
import {
    acceptShipBuyingOffer,
    acceptShipListing,
    acceptTransportContract,
    cancelShipListing,
    cancelTransportContract,
    dispatchConstructionShip,
    dispatchPassengerShip,
    dispatchShip,
    getAgentPlanetStorage,
    getShipMarketHistory,
    listAgentShips,
    listShipBuyingOffers,
    listShipListings,
    listTransportContracts,
    postShipBuyingOffer,
    postShipListing,
    postTransportContract,
} from './controller/ship';
import {
    getAgentDetail,
    getAgentFinancialHistory,
    getAgentFinancials,
    getAgentHistory,
    getAgentListSummaries,
    getAgentOverview,
    getAgentPlanetDetail,
    getArbitrageForResources,
    getCurrentTick,
    getLatestAgents,
    getLatestPlanetSummaries,
    getLoanConditions,
    getPlanetDetail,
    getPlanetPopulationHistory,
    getProductPriceHistory,
    getTickerEvents,
} from './controller/simulation';

import {
    acquireLicense,
    buildFacility,
    buildShipConstructionFacility,
    cancelBuyBid,
    cancelConstruction,
    cancelSellOffer,
    createAgent,
    expandFacility,
    expandShipConstructionFacility,
    getUser,
    getUserIdFromSession,
    getUsers,
    leaseClaim,
    quitClaim,
    repayLoan,
    requestLoan,
    setAutomation,
    setBuyBids,
    setFacilityScale,
    setSellOffers,
    setShipConstructionTarget,
    setWorkerAllocationTargets,
    updateUser,
} from './controller/user';
import { trpcRoot } from './trpcRoot';

const simulationRouter = trpcRoot.router({
    getCurrentTick: getCurrentTick(),
    getLatestPlanetSummaries: getLatestPlanetSummaries(),
    getLatestAgents: getLatestAgents(),
    getAgentListSummaries: getAgentListSummaries(),
    getAgentDetail: getAgentDetail(),
    getAgentOverview: getAgentOverview(),
    getAgentPlanetDetail: getAgentPlanetDetail(),
    getPlanetDetail: getPlanetDetail(),
    getPlanetPopulationHistory: getPlanetPopulationHistory(),
    getProductPriceHistory: getProductPriceHistory(),
    getAgentHistory: getAgentHistory(),
    getAgentFinancialHistory: getAgentFinancialHistory(),
    getLoanConditions: getLoanConditions(),
    getAgentFinancials: getAgentFinancials(),
    getPlanetOverview: getPlanetOverview(),
    getPlanetDemographics: getPlanetDemographics(),
    getPlanetEconomy: getPlanetEconomy(),
    getPlanetDemographicsFull: getPlanetDemographicsFull(),
    getPlanetMarket: getPlanetMarket(),
    getPlanetMarketOverview: getPlanetMarketOverview(),
    getPlanetClaims: getPlanetClaims(),
    getAgentClaims: getAgentClaims(),
    getTickerEvents: getTickerEvents(),
    getArbitrageForResources: getArbitrageForResources(),
    // historical endpoints removed
});

const protectedAppRouter = trpcRoot.router({
    getUsers: getUsers(),
    getUser: getUser(),
    updateUser: updateUser(),
    getUserIdFromSession: getUserIdFromSession(),
    createAgent: createAgent(),
    requestLoan: requestLoan(),
    repayLoan: repayLoan(),
    setAutomation: setAutomation(),
    setWorkerAllocationTargets: setWorkerAllocationTargets(),
    setSellOffers: setSellOffers(),
    cancelSellOffer: cancelSellOffer(),
    cancelBuyBid: cancelBuyBid(),
    cancelConstruction: cancelConstruction(),
    setBuyBids: setBuyBids(),
    buildFacility: buildFacility(),
    expandFacility: expandFacility(),
    setFacilityScale: setFacilityScale(),
    leaseClaim: leaseClaim(),
    quitClaim: quitClaim(),
    listAgentShips: listAgentShips(),
    listTransportContracts: listTransportContracts(),
    listShipBuyingOffers: listShipBuyingOffers(),
    listShipListings: listShipListings(),
    getShipMarketHistory: getShipMarketHistory(),
    postTransportContract: postTransportContract(),
    acceptTransportContract: acceptTransportContract(),
    cancelTransportContract: cancelTransportContract(),
    dispatchShip: dispatchShip(),
    dispatchConstructionShip: dispatchConstructionShip(),
    dispatchPassengerShip: dispatchPassengerShip(),
    postShipBuyingOffer: postShipBuyingOffer(),
    acceptShipBuyingOffer: acceptShipBuyingOffer(),
    postShipListing: postShipListing(),
    cancelShipListing: cancelShipListing(),
    acceptShipListing: acceptShipListing(),
    getAgentPlanetStorage: getAgentPlanetStorage(),
    buildShipConstructionFacility: buildShipConstructionFacility(),
    expandShipConstructionFacility: expandShipConstructionFacility(),
    setShipConstructionTarget: setShipConstructionTarget(),
    acquireLicense: acquireLicense(),
});

export const publicAccessibleRouter = trpcRoot.router({
    logs: logs(),
    health: health(),
    simulation: simulationRouter,
});

export const appRouter = trpcRoot.mergeRouters(publicAccessibleRouter, protectedAppRouter);
export type AppRouter = typeof appRouter;
