import { health } from './controller/health';
import { logs } from './controller/logs';
import {
    deleteAllRead,
    deleteMessage,
    getUnreadCount,
    listInbox,
    listRecipients,
    listSent,
    markAllRead,
    markRead,
    sendMessage,
} from './controller/message';
import {
    getAgentClaims,
    getPlanetClaims,
    getPlanetDemographics,
    getPlanetDemographicsFull,
    getPlanetEconomy,
    getPlanetMarket,
    getPlanetMarketOverview,
    getPlanetOverview,
    getPlanetScrapRecoveryRate,
} from './controller/planet';
import {
    acceptShipBuyingOffer,
    acceptShipListing,
    acceptTransportContract,
    cancelShipListing,
    cancelTransportContract,
    dispatchConstructionShip,
    dispatchPassengerShip,
    dispatchShip,
    getAgentPlanetStorage,
    getShipMarketHistory,
    listAgentShips,
    listShipBuyingOffers,
    listShipListings,
    listTransportContracts,
    postShipBuyingOffer,
    postShipListing,
    postTransportContract,
} from './controller/ship';
import {
    getAgentConditions,
    getAgentDetail,
    getAgentFinancialHistory,
    getAgentFinancials,
    getAgentHistory,
    getAgentListSummaries,
    getAgentOverview,
    getAgentPlanetDetail,
    getArbitrageForResources,
    getCurrentTick,
    getLatestAgents,
    getLatestPlanetSummaries,
    getListOfPlanets,
    getLoanConditions,
    getMyBankruptcy,
    getPlanetBufferHistory,
    getPlanetDetail,
    getPlanetEconomyHistory,
    getProductPriceHistory,
    getRawAgents,
    getTickerEvents,
    getUsedLogos,
    generateNewsReport,
} from './controller/simulation';

import {
    acquireLicense,
    acknowledgeBankruptcy,
    buildFacility,
    buildShipConstructionFacility,
    cancelBuyBid,
    cancelConstruction,
    cancelSellOffer,
    contractFacility,
    createAgent,
    expandFacility,
    expandShipConstructionFacility,
    getUser,
    getUserIdFromSession,
    getUsers,
    leaseClaim,
    quitClaim,
    repayLoan,
    requestLoan,
    setAutomation,
    setBuyBids,
    setConstructionSuspended,
    setFacilityScale,
    setSellOffers,
    setShipConstructionTarget,
    setWorkerAllocationTargets,
    updateUser,
} from './controller/user';
import { trpcRoot } from './trpcRoot';

const simulationRouter = trpcRoot.router({
    getCurrentTick: getCurrentTick(),
    getListOfPlanets: getListOfPlanets(),
    getLatestPlanetSummaries: getLatestPlanetSummaries(),
    getLatestAgents: getLatestAgents(),
    getAgentListSummaries: getAgentListSummaries(),
    getAgentDetail: getAgentDetail(),
    getAgentOverview: getAgentOverview(),
    getAgentPlanetDetail: getAgentPlanetDetail(),
    getAgentConditions: getAgentConditions(),
    getPlanetDetail: getPlanetDetail(),
    getPlanetEconomyHistory: getPlanetEconomyHistory(),
    getPlanetBufferHistory: getPlanetBufferHistory(),
    getProductPriceHistory: getProductPriceHistory(),
    getAgentHistory: getAgentHistory(),
    getAgentFinancialHistory: getAgentFinancialHistory(),
    getLoanConditions: getLoanConditions(),
    getAgentFinancials: getAgentFinancials(),
    getPlanetOverview: getPlanetOverview(),
    getPlanetDemographics: getPlanetDemographics(),
    getPlanetEconomy: getPlanetEconomy(),
    getPlanetDemographicsFull: getPlanetDemographicsFull(),
    getPlanetMarket: getPlanetMarket(),
    getPlanetMarketOverview: getPlanetMarketOverview(),
    getPlanetScrapRecoveryRate: getPlanetScrapRecoveryRate(),
    getPlanetClaims: getPlanetClaims(),
    getAgentClaims: getAgentClaims(),
    getTickerEvents: getTickerEvents(),
    getArbitrageForResources: getArbitrageForResources(),
    getRawAgents: getRawAgents(),
    getUsedLogos: getUsedLogos(),
    getMyBankruptcy: getMyBankruptcy(),
    generateNewsReport: generateNewsReport(),
    listAgentShips: listAgentShips(),
    listTransportContracts: listTransportContracts(),
    listShipBuyingOffers: listShipBuyingOffers(),
    listShipListings: listShipListings(),
    getShipMarketHistory: getShipMarketHistory(),
});

const messageRouter = trpcRoot.router({
    listRecipients: listRecipients(),
    listInbox: listInbox(),
    listSent: listSent(),
    getUnreadCount: getUnreadCount(),
    sendMessage: sendMessage(),
    markRead: markRead(),
    markAllRead: markAllRead(),
    deleteMessage: deleteMessage(),
    deleteAllRead: deleteAllRead(),
});

const protectedAppRouter = trpcRoot.router({
    getUsers: getUsers(),
    getUser: getUser(),
    updateUser: updateUser(),
    getUserIdFromSession: getUserIdFromSession(),
    createAgent: createAgent(),
    acknowledgeBankruptcy: acknowledgeBankruptcy(),
    requestLoan: requestLoan(),
    repayLoan: repayLoan(),
    setAutomation: setAutomation(),
    setWorkerAllocationTargets: setWorkerAllocationTargets(),
    setSellOffers: setSellOffers(),
    cancelSellOffer: cancelSellOffer(),
    cancelBuyBid: cancelBuyBid(),
    cancelConstruction: cancelConstruction(),
    setBuyBids: setBuyBids(),
    setConstructionSuspended: setConstructionSuspended(),
    buildFacility: buildFacility(),
    expandFacility: expandFacility(),
    contractFacility: contractFacility(),
    setFacilityScale: setFacilityScale(),
    leaseClaim: leaseClaim(),
    quitClaim: quitClaim(),
    postTransportContract: postTransportContract(),
    acceptTransportContract: acceptTransportContract(),
    cancelTransportContract: cancelTransportContract(),
    dispatchShip: dispatchShip(),
    dispatchConstructionShip: dispatchConstructionShip(),
    dispatchPassengerShip: dispatchPassengerShip(),
    postShipBuyingOffer: postShipBuyingOffer(),
    acceptShipBuyingOffer: acceptShipBuyingOffer(),
    postShipListing: postShipListing(),
    cancelShipListing: cancelShipListing(),
    acceptShipListing: acceptShipListing(),
    getAgentPlanetStorage: getAgentPlanetStorage(),
    buildShipConstructionFacility: buildShipConstructionFacility(),
    expandShipConstructionFacility: expandShipConstructionFacility(),
    setShipConstructionTarget: setShipConstructionTarget(),
    acquireLicense: acquireLicense(),
    message: messageRouter,
});

export const publicAccessibleRouter = trpcRoot.router({
    logs: logs(),
    health: health(),
    simulation: simulationRouter,
});

export const appRouter = trpcRoot.mergeRouters(publicAccessibleRouter, protectedAppRouter);
export type AppRouter = typeof appRouter;
