import {
    produceResourceType,
    beverageResourceType,
    cementResourceType,
    chemicalResourceType,
    clothingResourceType,
    coalResourceType,
    concreteResourceType,
    consumerElectronicsResourceType,
    copperOreResourceType,
    copperResourceType,
    cottonResourceType,
    crudeOilResourceType,
    electronicsResourceType,
    fabricResourceType,
    fuelResourceType,
    furnitureResourceType,
    glassResourceType,
    ironOreResourceType,
    limestoneResourceType,
    logsResourceType,
    lumberResourceType,
    machineryResourceType,
    packagingResourceType,
    paperResourceType,
    pesticideResourceType,
    pharmaceuticalResourceType,
    plasticResourceType,
    processedFoodResourceType,
    sandResourceType,
    siliconWaferResourceType,
    steelResourceType,
    stoneResourceType,
    vehicleResourceType,
    waterResourceType,
} from '../planet/resources';
import {
    administrativeServiceResourceType,
    constructionServiceResourceType,
    educationServiceResourceType,
    groceryServiceResourceType,
    healthcareServiceResourceType,
    logisticsServiceResourceType,
    maintenanceServiceResourceType,
    retailServiceResourceType,
} from '../planet/services';

const baselineFactor = 1;
export const initialMarketPrices: Record<string, number> = {
    [produceResourceType.name]: 6.5 * baselineFactor,
    [ironOreResourceType.name]: 0.5 * baselineFactor,
    [coalResourceType.name]: 0.5 * baselineFactor,
    [crudeOilResourceType.name]: 1.0 * baselineFactor,
    [logsResourceType.name]: 2.0 * baselineFactor,
    [stoneResourceType.name]: 0.5 * baselineFactor,
    [copperOreResourceType.name]: 0.5 * baselineFactor,
    [sandResourceType.name]: 0.5 * baselineFactor,
    [limestoneResourceType.name]: 0.5 * baselineFactor,
    [waterResourceType.name]: 2.0 * baselineFactor,
    [cottonResourceType.name]: 4.5 * baselineFactor,

    [steelResourceType.name]: 1.5 * baselineFactor,
    [lumberResourceType.name]: 3.5 * baselineFactor,
    [copperResourceType.name]: 2.0 * baselineFactor,
    [glassResourceType.name]: 1.0 * baselineFactor,
    [cementResourceType.name]: 1.5 * baselineFactor,
    [plasticResourceType.name]: 1.5 * baselineFactor,
    [chemicalResourceType.name]: 6.0 * baselineFactor,
    [fuelResourceType.name]: 1.5 * baselineFactor,
    [fabricResourceType.name]: 8.0 * baselineFactor,
    [processedFoodResourceType.name]: 22.0 * baselineFactor,
    [beverageResourceType.name]: 11.0 * baselineFactor,
    [paperResourceType.name]: 7.0 * baselineFactor,
    [pesticideResourceType.name]: 21.5 * baselineFactor,
    [concreteResourceType.name]: 2.5 * baselineFactor,
    [siliconWaferResourceType.name]: 6.5 * baselineFactor,
    [packagingResourceType.name]: 10.0 * baselineFactor,

    [clothingResourceType.name]: 17.0 * baselineFactor,
    [furnitureResourceType.name]: 13.0 * baselineFactor,
    [electronicsResourceType.name]: 13.0 * baselineFactor,
    [consumerElectronicsResourceType.name]: 26.0 * baselineFactor,
    [machineryResourceType.name]: 7.0 * baselineFactor,
    [vehicleResourceType.name]: 34.0 * baselineFactor,
    [pharmaceuticalResourceType.name]: 133.0 * baselineFactor,

    [groceryServiceResourceType.name]: 6.0 * baselineFactor,
    [healthcareServiceResourceType.name]: 5.5 * baselineFactor,
    [administrativeServiceResourceType.name]: 1.5 * baselineFactor,
    [logisticsServiceResourceType.name]: 1.0 * baselineFactor,
    [retailServiceResourceType.name]: 4.5 * baselineFactor,
    [constructionServiceResourceType.name]: 10.5 * baselineFactor,
    [educationServiceResourceType.name]: 3.0 * baselineFactor,
    [maintenanceServiceResourceType.name]: 3.0 * baselineFactor,
};
