import { nextRandom } from '../utils/stochasticRound';
import type { FacilityType } from '../planet/productionFacilities';

const CORPORATE_FORMS = [
    'Co',
    'Corp',
    'Inc',
    'Ltd',
    'Group',
    'Ventures',
    'Holdings',
    'Enterprises',
    'Partners',
    'Industries',
    'Dynamics',
    'Solutions',
    'Systems',
    'Technologies',
    'Resources',
];

const WORD_POOLS: Record<FacilityType, { stems: string[] }> = {
    coalMine: {
        stems: [
            'Blackrock Coal',
            'Carbon Energy',
            'Deep Seam',
            'Anthracite Mining',
            'Coalfield',
            'Northern Seam',
            'Coal Valley',
            'Mountain Coal',
            'Iron Vein',
            'Dark Mineral',
            'Shale Creek',
            'Bedrock Mining',
            'Coking Coal',
            'Carbon River',
            'MineCorp',
        ],
    },
    oilWell: {
        stems: [
            'PetroGlobal',
            'Continental Oil',
            'North Sea Energy',
            'Gulf Petroleum',
            'Arctic Oil',
            'Pacific Offshore',
            'Deep Horizon',
            'Inland Petroleum',
            'Delta Oil',
            'Gulf Coast',
            'Northern Oil',
            'Crude Energy',
            'PetroEx',
            'Oil Field',
            'DrillTech',
        ],
    },
    loggingCamp: {
        stems: [
            'Great Northern Timber',
            'Pacific Lumber',
            'Boreal Wood',
            'Tropical Forest',
            'Redwood Harvesting',
            'Nordic Forestry',
            'Taiga Timber',
            'Hardwood Estates',
            'Evergreen Logging',
            'Cedar Ridge',
            'Pine Forest',
            'Ironwood',
            'Maple Leaf Lumber',
            'Birch Creek',
            'Forest Prime',
        ],
    },
    stoneQuarry: {
        stems: [
            'Granite Quarrying',
            'Basalt Rock',
            'Alpine Stone',
            'Continental Quarries',
            'Bedrock Mining',
            'Mesa Stone',
            'Stone Age',
            'Rock Solid',
            'Canyon Stone',
            'Crag Mining',
            'Summit Quarries',
            'StoneWorks',
        ],
    },
    copperMine: {
        stems: [
            'Copper Basin Mining',
            'Pacific Copper',
            'Andean Copper',
            'Red Dragon Minerals',
            'Atlas Copper',
            'Copper Field',
            'Bronze Age Mining',
            'Copper King',
            'Rust Mountain',
            'Ore Valley',
        ],
    },
    sandMine: {
        stems: [
            'Desert Sand',
            'Sahara Sand',
            'Coastal Aggregates',
            'Riviera Minerals',
            'Golden Dunes',
            'Silica Resources',
            'White Sand',
            'Beach Minerals',
            'Dune Extraction',
            'Quartz Sand',
        ],
    },
    limestoneQuarry: {
        stems: [
            'Alpine Stone',
            'Karst Quarry',
            'Coral Rock Mining',
            'White Cliffs Materials',
            'Limestone Dynamics',
            'Calcium Rock',
            'Sediment Mining',
            'Chalk Ridge',
            'LimeStone',
            'Marl Basin',
        ],
    },
    cottonFarm: {
        stems: [
            'Cotton World',
            'Textile Fields',
            'Delta Cotton',
            'Southern Plains Cotton',
            'Nile Cotton',
            'Indus Valley Textiles',
            'Cotton Empire',
            'Prairie Fiber',
            'Sun Belt Cotton',
            'Golden Fleece',
            'White Gold',
            'Cotton Bloom',
            'Fiber Fields',
            'Cotton State',
            'Boll Weevil',
        ],
    },
    waterFacility: {
        stems: [
            'AquaGlobal',
            'Pure Water',
            'H2O Ventures',
            'Continental Water',
            'Blue Ocean Utilities',
            'Fresh Source',
            'AquaTech',
            'Hydro Systems',
            'Clearwater Utilities',
            'Riviera Water',
            'Spring Water',
            'Mountain Aqua',
            'Water Works',
            'Deep Well',
            'Clear Springs',
        ],
    },
    ironMine: {
        stems: [
            'Ironworks Global',
            'Deep Core Mining',
            'Red Earth Mines',
            'Steel Source',
            'Iron Ridge',
            'Magnetite Mining',
            'Ferrum Extraction',
            'Highland Iron',
            'Ore Masters',
            'Taconite Mining',
            'Iron Mountain',
            'Rust Belt Mining',
            'Pig Iron',
            'Smelt Source',
            'Hematite',
        ],
    },
    ironSmelter: {
        stems: [
            'Atlas Steel Works',
            'Meridian Steel',
            'Nova Metals',
            'Forge Masters',
            'Titan Steel',
            'Vulcan Metals',
            'Ironclad Industries',
            'Red Forge',
            'Steel Dynamics',
            'Molten Steel',
            'Crucible Metals',
            'Alloy Masters',
            'Blast Furnace',
            'Metal Works',
            'Steel Mill',
        ],
    },
    copperSmelter: {
        stems: [
            'World Copper Smelting',
            'Pacific Metals',
            'Copper Dynamics',
            'Electro Metals',
            'Conductive Corp',
            'Cathode Masters',
            'Refining Ventures',
            'Bronze Age Metals',
            'Copper Ridge',
            'AlloyCraft',
            'Cu Refining',
            'SmeltCo',
        ],
    },
    oilRefinery: {
        stems: [
            'Horizon Refinery',
            'Global Petrochemicals',
            'Coastal Refining',
            'Inland Refinery',
            'Continental Petrochem',
            'NorthWest Refining',
            'Gulf Coast Refineries',
            'Pacific Derivatives',
            'Midland Refinery',
            'TarSands Processing',
            'HydroCarbon',
            'Distillation Masters',
            'Crackers Inc',
            'Refinery Corp',
            'Fossil Fuel',
        ],
    },
    sawmill: {
        stems: [
            'Global Sawmills',
            'Timber Products',
            'Pacific Milling',
            'Hardwood Processing',
            'Lumber Masters',
            'Northern Mills',
            'Forest Products',
            'Cedar Milling',
            'Pine Ridge Sawmill',
            'Boreal Processing',
            'Timberline',
            'Woodland Milling',
            'Sawdust Co',
            'Plank Works',
            'Wood Cutter',
        ],
    },
    cementPlant: {
        stems: [
            'Cement Giant',
            'Continental Cement',
            'Urban Concrete',
            'Grey Stone',
            'Portland Cement',
            'Clinker Corp',
            'Building Stone',
            'Pacific Cement',
            'Alpine Cement',
            'MegaMix',
            'Foundation Materials',
            'Bridge Cement',
            'Concrete Base',
            'Calcium Silicate',
            'Kiln Masters',
        ],
    },
    glassFactory: {
        stems: [
            'Glass World',
            'Crystal Dynamics',
            'Clear Vision Glass',
            'Silicon Glass',
            'Glazing Solutions',
            'Optical Glass',
            'Continental Glass',
            'Palace Glass',
            'ArcticGlass',
            'Flint Glass',
            'Tempered Corp',
            'Float Glass',
            'Glassworks',
            'Pane Masters',
            'Prism Glass',
        ],
    },
    pesticidePlant: {
        stems: [
            'GreenChem',
            'CropGuard',
            'BioShield Chemicals',
            'Field Protect',
            'AgriDefense',
            'Pest Control',
            'CropChem',
            'FarmShield',
            'AgroChem',
            'PlantProtect',
            'BioCide',
            'BugOff',
        ],
    },
    paperMill: {
        stems: [
            'Paper World',
            'Northern Paper Mills',
            'Pacific Pulp',
            'Newsprint Dynamics',
            'Cellulose Masters',
            'Paper Mill',
            'Ream Corp',
            'Pulp and Paper',
            'Stationery Co',
            'Wood Pulp',
        ],
    },
    textileMill: {
        stems: [
            'Global Textiles',
            'FiberCraft',
            'Woven World',
            'Continental Fabric',
            'Loom Masters',
            'Thread and Fiber',
            'Pacific Weaving',
            'Spinning Technologies',
            'Mill Stream',
            'Fiber Dynamics',
            'Eastern Textiles',
            'Yarn Masters',
            'Textile Mill',
            'Cloth Works',
            'Fabric Co',
        ],
    },
    concretePlant: {
        stems: [
            'Concrete Giant',
            'Urban Materials',
            'Stone Age Building',
            'MixMaster',
            'Aggregate Solutions',
            'Foundation Corp',
            'Structural Mix',
            'Precast Dynamics',
            'ReadyMix',
            'ConcreteTech',
            'Block and Slab',
            'Paving Masters',
            'Pour Masters',
            'Solid Mix',
            'Quick Pour',
        ],
    },
    foodProcessor: {
        stems: [
            'World Foods',
            'Continental Food',
            'Pacific Provisions',
            'Harvest Processing',
            'FoodTech',
            'Nourish Corp',
            'Global Provisions',
            'Ready Meals',
            'Processed Foods',
            'Canned Goods',
            'FoodChain',
            'Nutrition Masters',
            'Preserve Co',
            'Food Factory',
            'Meal Prep',
        ],
    },
    beveragePlant: {
        stems: [
            'Beverage Planet',
            'Freshdrink',
            'ThirstQuench',
            'LiquidRefresh',
            'Bottle Factory',
            'DrinkWorks',
            'H2O Plus',
            'Sunrise Beverages',
            'Pacific Drinks',
            'Continental Beverages',
            'Sip Well',
            'Quench Corp',
            'Brew Masters',
            'Hydration Co',
            'Fizz Corp',
        ],
    },
    pharmaPlant: {
        stems: [
            'PharmaGlobal',
            'MedLife',
            'BioSynth',
            'CureAll Pharmaceuticals',
            'Remedy Corp',
            'HealTech',
            'Compound Dynamics',
            'Generic Meds',
            'Research Pharma',
            'Vital Drugs',
            'DrugCo',
            'PharmaCorp',
            'MediSynth',
            'Pill Corp',
            'Therapeutics',
        ],
    },
    clothingFactory: {
        stems: [
            'Fashion World',
            'Garment Masters',
            'Global Apparel',
            'ThreadWorks',
            'StitchRight',
            'ClothCraft',
            'WearTech',
            'StyleMakers',
            'Fabric Arts',
            'Couture Industries',
            'Ready-to-Wear',
            'Drape and Stitch',
            'Fashion Co',
            'Apparel Corp',
            'Sew Tech',
        ],
    },
    furnitureFactory: {
        stems: [
            'Home Furnishings',
            'Woodcraft International',
            'LivingSpace',
            'HomeWorks',
            'Comfort Furniture',
            'Nordic Design',
            'Wooden Dreams',
            'Casa Furniture',
            'GoodHome',
            'Modern Furnishings',
            'Classic Wood',
            'Interior Masters',
            'Furniture Co',
            'Table Works',
            'Chair Masters',
        ],
    },
    electronicsFactory: {
        stems: [
            'Silicon Dynamics',
            'Global Electronics',
            'Circuit World',
            'Component Masters',
            'PCB Dynamics',
            'Micro Elements',
            'TechParts',
            'Board Masters',
            'ChipWorks',
            'ElectroBase',
            'SemiConductor',
            'MicroCircuit',
            'Transistor Co',
            'Board Tech',
            'Logic Parts',
        ],
    },
    itDevicesFactory: {
        stems: [
            'TechVision',
            'Gadget World',
            'Device Planet',
            'SmartTech',
            'DigitalEdge',
            'Consumer Electronics',
            'NextGen Devices',
            'Pixel Perfect',
            'ElectoHome',
            'TechLife',
            'Digital Masters',
            'SmartHome',
            'Gadget Co',
            'ElectroCorp',
            'TechBox',
        ],
    },
    machineryFactory: {
        stems: [
            'Mech Industries',
            'Heavy Works International',
            'Precision Engineering',
            'Iron Horse Machinery',
            'Gear Works',
            'MachineCorp',
            'Industrial Mech',
            'Tool Masters',
            'Engine Works',
            'Hydraulic Corp',
        ],
    },
    vehicleFactory: {
        stems: [
            'Automotion',
            'DriveTech Motors',
            'Precision Parts',
            'WheelWorks',
            'Motor Masters',
            'Auto Craft',
            'Vehicle Corp',
            'Assembly Line',
            'Chassis Co',
            'Turbine Motors',
        ],
    },
    agriculturalFacility: {
        stems: [
            'AgroTech Global',
            'Precision Farming',
            'Yield Max',
            'GrowSmart',
            'Crop Science',
            'AgroVentures',
            'Cultivar Corp',
            'FarmTech',
            'PrecisionCrop',
            'HighYield Farms',
            'CropDynamics',
            'Agronomics',
            'Smart Farm',
            'BioGrow',
            'HydroPonics',
        ],
    },
    packagingPlant: {
        stems: [
            'PackGlobal',
            'Wrap World',
            'BoxMakers',
            'Container Corp',
            'PackArt',
            'ShipRight',
            'Pack Dynamics',
            'BulkPack',
            'Seal Masters',
            'WrapTech',
            'PackSolutions',
            'Crate and Box',
            'Package Co',
            'Box Corp',
            'Pallet Works',
        ],
    },
    administrativeCenter: {
        stems: [
            'Global Admin Services',
            'Civic Solutions',
            'Metro Admin Group',
            'BackOffice',
            'AdminWorld',
            'Corporate Services',
            'BizAdmin',
            'Central Office',
            'OfficeTech',
            'AdminPro',
            'Enterprise Services',
            'SupportHub',
            'Admin Corps',
            'Business Support',
            'Office Works',
        ],
    },
    logisticsHub: {
        stems: [
            'Swift Logistics',
            'Global Freight',
            'Nexus Distribution',
            'MoveIt',
            'FlowChain',
            'ShipFast',
            'RouteMax',
            'Cargo Masters',
            'DeliverAll',
            'FreightWorks',
            'TransitHub',
            'LogiFlow',
            'Freight Corp',
            'Supply Chain',
            'Move Corp',
        ],
    },
    constructionFacility: {
        stems: [
            'BuildRight Services',
            'Urban Construct',
            'Global Builders',
            'Foundation Works',
            'ErectAll',
            'SkyHigh Construction',
            'GroundWork',
            'MegaBuild',
            'Construct Masters',
            'TowerBuilders',
            'BlueCollar Services',
            'EliteBuild',
            'Build Corp',
            'Construct Co',
            'Rise and Build',
        ],
    },
    groceryChain: {
        stems: [
            'FreshMart Chain',
            'World Grocery',
            'Daily Basket',
            'Metro Grocers',
            'SuperFresh',
            'GrocerWorld',
            'The Food Depot',
            'FoodFirst',
            'Pantry Masters',
            'FreshChoice',
            'BigBasket',
            'GrocerPlus',
            'Market Co',
            'Fresh Foods',
            'Corner Grocery',
        ],
    },
    retailChain: {
        stems: [
            'OmniRetail',
            'Global Shops',
            'Prime Retail Chain',
            'MegaMart',
            'ShopWorld',
            'RetailFirst',
            'StoreChain',
            'OpenMart',
            'ValueShop',
            'BuyMore',
            'ShopSmart',
            'BargainWorld',
            'RetailCo',
            'MarketPlace',
            'BuyRight',
        ],
    },
    hospital: {
        stems: [
            'HealthNet',
            'Global Care',
            'Metro Health Group',
            'CureAll Clinics',
            'WellBeing',
            'MedCenter',
            'LifeHealth',
            'CareFirst',
            'Vitality Health',
            'HealAll',
            'MediGroup',
            'WellnessFirst',
            'Health Corp',
            'MediCare',
            'DocTor Group',
        ],
    },
    educationCenter: {
        stems: ['Education World', 'Education First', 'Education Network', 'Education Group', 'Education Global'],
    },
    maintenanceFacility: {
        stems: [
            'Maintenance World',
            'Maintenance First',
            'Maintenance Network',
            'Maintenance Group',
            'Maintenance Global',
        ],
    },
    siliconWaferFactory: {
        stems: [
            'WaferTech',
            'Global Wafers',
            'Silicon Masters',
            'PureSilicon',
            'Wafer Dynamics',
            'CrystalSilicon',
            'SemiConductor',
            'Wafer Works',
            'SiliconEdge',
            'ChipStart',
            'WaferPro',
            'Silicon Valley',
            'Crystal Corp',
            'Ingot Works',
            'Doping Co',
        ],
    },
};

function generateCompanyName(facilityType: FacilityType, index: number): string {
    const pool = WORD_POOLS[facilityType];
    if (!pool) {
        return `${facilityType}-${index}`;
    }

    const existingNames = [...(NAMES[facilityType] ?? [])];

    const stem = pool.stems[Math.floor(nextRandom() * pool.stems.length)];

    if (nextRandom() < 0.5 || existingNames.some((n) => n.startsWith(stem))) {
        const form = CORPORATE_FORMS[Math.floor(nextRandom() * CORPORATE_FORMS.length)];
        const candidate = `${stem} ${form}`;
        if (!existingNames.includes(candidate) && !existingNames.some((n) => n.startsWith(stem) && n.endsWith(form))) {
            return candidate;
        }
    }

    const form = CORPORATE_FORMS[Math.floor(nextRandom() * CORPORATE_FORMS.length)];
    const suffix = Math.floor(nextRandom() * 100);
    return `${stem} ${form} ${suffix}`;
}

export function getNamesFor(facilityType: FacilityType, count: number): string[] {
    const existing = NAMES[facilityType] ?? [];

    if (count <= existing.length) {
        return existing.slice(0, count);
    }

    const result = [...existing];
    const generated = new Set(result);

    let i = 0;
    while (result.length < count) {
        const name = generateCompanyName(facilityType, i);
        if (!generated.has(name)) {
            generated.add(name);
            result.push(name);
        }
        i++;
    }

    return result;
}

export const NAMES: Record<string, string[]> = {
    tankerTransport: [],
    coalMine: [
        'Blackrock Coal Co',
        'Carbon Energy Group',
        'Deep Seam Coal',
        'Anthracite Mining Corp',
        'Coalfield Ventures',
        'Northern Seam Ltd',
        'Coal Valley Co',
    ],
    oilWell: [
        'PetroGlobal Corp',
        'Continental Oil Inc',
        'North Sea Energy',
        'Gulf Petroleum Ltd',
        'Arctic Oil Co',
        'Pacific Offshore Inc',
        'Deep Horizon Oil',
        'Inland Petroleum Corp',
        'Delta Oil & Gas',
        'Gulf Coast Oil',
        'Northern Oil & Gas',
    ],
    loggingCamp: [
        'Great Northern Timber',
        'Pacific Lumber Co',
        'Boreal Wood Products',
        'Tropical Forest Co',
        'Redwood Harvesting',
        'Nordic Forestry Ltd',
        'Taiga Timber Corp',
        'Hardwood Estates',
        'Evergreen Logging Inc',
        'Cedar Ridge Timber',
    ],
    stoneQuarry: [
        'Granite Quarrying Corp',
        'Basalt Rock Corp',
        'Alpine Stone Ltd',
        'Continental Quarries',
        'Bedrock Mining Co',
        'Mesa Stone Corp',
    ],
    copperMine: [
        'Copper Basin Mining',
        'Pacific Copper Co',
        'Andean Copper Mines',
        'Red Dragon Minerals',
        'Atlas Copper Ltd',
    ],
    sandMine: [
        'Desert Sand Corp',
        'Sahara Sand Co',
        'Coastal Aggregates Ltd',
        'Riviera Minerals',
        'Golden Dunes Mining',
        'Silica Resources Corp',
    ],
    limestoneQuarry: [
        'Alpine Stone Corp',
        'Karst Quarry Co',
        'Coral Rock Mining',
        'White Cliffs Materials',
        'Limestone Dynamics Ltd',
    ],
    clayMine: ['Delta Clay Mining', 'Plains Clay Corp', 'Red Earth Clay Ltd'],
    cottonFarm: [
        'Cotton World Corp',
        'Textile Fields Ltd',
        'Delta Cotton Farms',
        'Southern Plains Cotton',
        'Nile Cotton Co',
        'Indus Valley Textiles',
        'Cotton Empire Inc',
        'Prairie Fiber Corp',
        'Sun Belt Cotton',
        'Golden Fleece Farms',
    ],
    waterExtractionFacility: [
        'AquaGlobal Corp',
        'Pure Water Inc',
        'H2O Ventures',
        'Continental Water Corp',
        'Blue Ocean Utilities',
        'Fresh Source Ltd',
        'AquaTech Corp',
        'Hydro Systems Inc',
        'Clearwater Utilities',
        'Riviera Water Co',
    ],
    ironExtractionFacility: [
        'Ironworks Global',
        'Deep Core Mining',
        'Red Earth Mines',
        'Steel Source Co',
        'Iron Ridge Corp',
        'Magnetite Mining Inc',
        'Ferrum Extraction Ltd',
        'Highland Iron Co',
        'Ore Masters Corp',
        'Taconite Mining Inc',
    ],
    ironSmelter: [
        'Atlas Steel Works',
        'Meridian Steel Corp',
        'Nova Metals Group',
        'Forge Masters Inc',
        'Titan Steel Ltd',
        'Vulcan Metals Corp',
        'Ironclad Industries',
        'Red Forge Co',
        'Steel Dynamics Ltd',
        'Molten Steel Corp',
        'Crucible Metals Inc',
        'Alloy Masters Ltd',
    ],
    copperSmelter: [
        'World Copper Smelting',
        'Pacific Metals Corp',
        'Copper Dynamics Ltd',
        'Electro Metals Inc',
        'Conductive Corp',
        'Cathode Masters Ltd',
        'Refining Ventures',
        'Bronze Age Metals',
        'Copper Ridge Corp',
        'AlloyCraft Inc',
    ],
    oilRefinery: [
        'Horizon Refinery Corp',
        'Global Petrochemicals',
        'Coastal Refining Ltd',
        'Inland Refinery Co',
        'Continental Petrochem',
        'NorthWest Refining',
        'Gulf Coast Refineries',
        'Pacific Derivatives Corp',
        'Midland Refinery Group',
        'TarSands Processing',
        'HydroCarbon Corp',
        'Distillation Masters Ltd',
    ],
    sawmill: [
        'Global Sawmills Corp',
        'Timber Products Co',
        'Pacific Milling Inc',
        'Hardwood Processing Ltd',
        'Lumber Masters Corp',
        'Northern Mills Ltd',
        'Forest Products Inc',
        'Cedar Milling Co',
        'Pine Ridge Sawmill',
        'Boreal Processing Ltd',
        'Timberline Corp',
        'Woodland Milling Inc',
    ],
    cementPlant: [
        'Cement Giant Corp',
        'Continental Cement',
        'Urban Concrete Inc',
        'Grey Stone Corp',
        'Portland Cement Ltd',
        'Clinker Corp',
        'Building Stone Inc',
        'Pacific Cement Co',
        'Alpine Cement Ltd',
        'MegaMix Corp',
        'Foundation Materials Inc',
        'Bridge Cement Ltd',
    ],
    glassFactory: [
        'Glass World Ltd',
        'Crystal Dynamics Corp',
        'Clear Vision Glass',
        'Silicon Glass Inc',
        'Glazing Solutions Corp',
        'Optical Glass Ltd',
        'Continental Glass Corp',
        'Palace Glass Inc',
        'ArcticGlass Ltd',
        'Flint Glass Corp',
    ],
    pesticidePlant: ['GreenChem Ltd', 'CropGuard Corp', 'BioShield Chemicals', 'Field Protect Inc', 'AgriDefense Ltd'],
    paperMill: [
        'Paper World Inc',
        'Northern Paper Mills',
        'Pacific Pulp Corp',
        'Newsprint Dynamics',
        'Cellulose Masters Ltd',
    ],
    textileMill: [
        'Global Textiles Inc',
        'FiberCraft Corp',
        'Woven World Ltd',
        'Continental Fabric Corp',
        'Loom Masters Inc',
        'Thread & Fiber Co',
        'Pacific Weaving Corp',
        'Spinning Technologies Ltd',
        'Mill Stream Corp',
        'Fiber Dynamics Inc',
        'Eastern Textiles Ltd',
        'Yarn Masters Corp',
    ],
    concretePlant: [
        'Concrete Giant Corp',
        'Urban Materials Inc',
        'Stone Age Building',
        'MixMaster Corp',
        'Aggregate Solutions Ltd',
        'Foundation Corp',
        'Structural Mix Inc',
        'Precast Dynamics',
        'ReadyMix Co',
        'ConcreteTech Ltd',
        'Block & Slab Corp',
        'Paving Masters Inc',
    ],
    foodProcessingPlant: [
        'World Foods Corp',
        'Continental Food Inc',
        'Pacific Provisions Ltd',
        'Harvest Processing Corp',
        'FoodTech Inc',
        'Nourish Corp',
        'Global Provisions Ltd',
        'Ready Meals Corp',
        'Processed Foods Inc',
        'Canned Goods Corp',
        'FoodChain Ltd',
        'Nutrition Masters Inc',
    ],
    beveragePlant: [
        'Beverage Planet Inc',
        'Freshdrink Co',
        'ThirstQuench Corp',
        'LiquidRefresh Ltd',
        'Bottle Factory Corp',
        'DrinkWorks Inc',
        'H2O Plus Corp',
        'Sunrise Beverages',
        'Pacific Drinks Ltd',
        'Continental Beverages Corp',
    ],
    pharmaceuticalPlant: [
        'PharmaGlobal Corp',
        'MedLife Corp',
        'BioSynth Inc',
        'CureAll Pharmaceuticals',
        'Remedy Corp',
        'HealTech Ltd',
        'Compound Dynamics',
        'Generic Meds Inc',
        'Research Pharma Corp',
        'Vital Drugs Ltd',
    ],
    clothingFactory: [
        'Fashion World Ltd',
        'Garment Masters Corp',
        'Global Apparel Inc',
        'ThreadWorks Ltd',
        'StitchRight Corp',
        'ClothCraft Inc',
        'WearTech Corp',
        'StyleMakers Ltd',
        'Fabric Arts Corp',
        'Couture Industries Inc',
        'Ready-to-Wear Corp',
        'Drape & Stitch Ltd',
    ],
    furnitureFactory: [
        'Home Furnishings Corp',
        'Woodcraft International',
        'LivingSpace Corp',
        'HomeWorks Ltd',
        'Comfort Furniture Inc',
        'Nordic Design Corp',
        'Wooden Dreams Ltd',
        'Casa Furniture Inc',
        'GoodHome Corp',
        'Modern Furnishings Ltd',
        'Classic Wood Corp',
        'Interior Masters Inc',
    ],
    electronicComponentFactory: [
        'Silicon Dynamics Corp',
        'Global Electronics Inc',
        'Circuit World Ltd',
        'Component Masters Corp',
        'PCB Dynamics Inc',
        'Micro Elements Ltd',
        'TechParts Corp',
        'Board Masters Inc',
        'ChipWorks Ltd',
        'ElectroBase Corp',
    ],
    consumerElectronicsFactory: [
        'TechVision Corp',
        'Gadget World Inc',
        'Device Planet Ltd',
        'SmartTech Corp',
        'DigitalEdge Inc',
        'Consumer Electronics Ltd',
        'NextGen Devices Corp',
        'Pixel Perfect Inc',
        'ElectoHome Ltd',
        'TechLife Corp',
        'Digital Masters Inc',
        'SmartHome Corp',
    ],
    machineryFactory: [
        'Mech Industries Ltd',
        'Heavy Works International',
        'Precision Engineering Co',
        'Iron Horse Machinery',
        'Gear Works Corp',
    ],
    vehicleFactory: [
        'Automotion Corp',
        'DriveTech Motors',
        'Precision Parts Co',
        'WheelWorks Corp',
        'Motor Masters Ltd',
    ],
    intensiveFarmFacility: [
        'AgroTech Global',
        'Precision Farming Inc',
        'Yield Max Corp',
        'GrowSmart Ltd',
        'Crop Science Corp',
        'AgroVentures Inc',
        'Cultivar Corp',
        'FarmTech Ltd',
        'PrecisionCrop Inc',
        'HighYield Farms',
        'CropDynamics Corp',
        'Agronomics Ltd',
    ],
    packagingPlant: [
        'PackGlobal Corp',
        'Wrap World Inc',
        'BoxMakers Ltd',
        'Container Corp',
        'PackArt Inc',
        'ShipRight Corp',
        'Pack Dynamics Ltd',
        'BulkPack Corp',
        'Seal Masters Inc',
        'WrapTech Corp',
        'PackSolutions Ltd',
        'Crate & Box Corp',
    ],
    administrativeCenter: [
        'Global Admin Services',
        'Civic Solutions Corp',
        'Metro Admin Group',
        'BackOffice Corp',
        'AdminWorld Inc',
        'Corporate Services Ltd',
        'BizAdmin Corp',
        'Central Office Inc',
        'OfficeTech Corp',
        'AdminPro Ltd',
        'Enterprise Services Corp',
        'SupportHub Inc',
    ],
    logisticsHub: [
        'Swift Logistics Corp',
        'Global Freight Ltd',
        'Nexus Distribution Inc',
        'MoveIt Corp',
        'FlowChain Ltd',
        'ShipFast Corp',
        'RouteMax Inc',
        'Cargo Masters Ltd',
        'DeliverAll Corp',
        'FreightWorks Inc',
        'TransitHub Ltd',
        'LogiFlow Corp',
    ],
    constructionService: [
        'BuildRight Services',
        'Urban Construct Co',
        'Global Builders Corp',
        'Foundation Works Inc',
        'ErectAll Ltd',
        'SkyHigh Construction',
        'GroundWork Corp',
        'MegaBuild Inc',
        'Construct Masters Ltd',
        'TowerBuilders Corp',
        'BlueCollar Services Inc',
        'EliteBuild Corp',
    ],
    groceryChain: [
        'FreshMart Chain',
        'World Grocery Corp',
        'Daily Basket Inc',
        'Metro Grocers Ltd',
        'SuperFresh Corp',
        'GrocerWorld Inc',
        'The Food Depot',
        'FoodFirst Corp',
        'Pantry Masters Ltd',
        'FreshChoice Inc',
        'BigBasket Corp',
        'GrocerPlus Ltd',
    ],
    retailChain: [
        'OmniRetail Corp',
        'Global Shops Ltd',
        'Prime Retail Chain',
        'MegaMart Inc',
        'ShopWorld Corp',
        'RetailFirst Ltd',
        'StoreChain Corp',
        'OpenMart Inc',
        'ValueShop Corp',
        'BuyMore Ltd',
        'ShopSmart Corp',
        'BargainWorld Inc',
    ],
    hospital: [
        'HealthNet Corp',
        'Global Care Ltd',
        'Metro Health Group',
        'CureAll Clinics',
        'WellBeing Corp',
        'MedCenter Inc',
        'LifeHealth Corp',
        'CareFirst Ltd',
        'Vitality Health Corp',
        'HealAll Inc',
        'MediGroup Ltd',
        'WellnessFirst Corp',
    ],
    siliconWaferFactory: [
        'WaferTech Corp',
        'Global Wafers Inc',
        'Silicon Masters Ltd',
        'PureSilicon Corp',
        'Wafer Dynamics Inc',
        'CrystalSilicon Ltd',
        'SemiConductor Corp',
        'Wafer Works Inc',
        'SiliconEdge Ltd',
        'ChipStart Corp',
    ],
};
