export const NAMES: Record<string, string[]> = {
    tankerTransport: [],
    coalMine: [
        'Blackrock Coal Co',
        'Carbon Energy Group',
        'Deep Seam Coal',
        'Anthracite Mining Corp',
        'Coalfield Ventures',
        'Northern Seam Ltd',
    ],
    oilWell: [
        'PetroGlobal Corp',
        'Continental Oil Inc',
        'North Sea Energy',
        'Gulf Petroleum Ltd',
        'Arctic Oil Co',
        'Pacific Offshore Inc',
        'Deep Horizon Oil',
        'Inland Petroleum Corp',
        'Delta Oil & Gas',
    ],
    loggingCamp: [
        'Great Northern Timber',
        'Pacific Lumber Co',
        'Boreal Wood Products',
        'Tropical Forest Co',
        'Redwood Harvesting',
        'Nordic Forestry Ltd',
        'Taiga Timber Corp',
        'Hardwood Estates',
        'Evergreen Logging Inc',
        'Cedar Ridge Timber',
    ],
    stoneQuarry: [
        'Granite Quarrying Corp',
        'Basalt Rock Corp',
        'Alpine Stone Ltd',
        'Continental Quarries',
        'Bedrock Mining Co',
        'Mesa Stone Corp',
    ],
    copperMine: [
        'Copper Basin Mining',
        'Pacific Copper Co',
        'Andean Copper Mines',
        'Red Dragon Minerals',
        'Atlas Copper Ltd',
    ],
    sandMine: [
        'Desert Sand Corp',
        'Sahara Sand Co',
        'Coastal Aggregates Ltd',
        'Riviera Minerals',
        'Golden Dunes Mining',
        'Silica Resources Corp',
    ],
    limestoneQuarry: [
        'Alpine Stone Corp',
        'Karst Quarry Co',
        'Coral Rock Mining',
        'White Cliffs Materials',
        'Limestone Dynamics Ltd',
    ],
    clayMine: ['Delta Clay Mining', 'Plains Clay Corp', 'Red Earth Clay Ltd'],
    cottonFarm: [
        'Cotton World Corp',
        'Textile Fields Ltd',
        'Delta Cotton Farms',
        'Southern Plains Cotton',
        'Nile Cotton Co',
        'Indus Valley Textiles',
        'Cotton Empire Inc',
        'Prairie Fiber Corp',
        'Sun Belt Cotton',
        'Golden Fleece Farms',
    ],
    waterExtractionFacility: [
        'AquaGlobal Corp',
        'Pure Water Inc',
        'H2O Ventures',
        'Continental Water Corp',
        'Blue Ocean Utilities',
        'Fresh Source Ltd',
        'AquaTech Corp',
        'Hydro Systems Inc',
        'Clearwater Utilities',
        'Riviera Water Co',
    ],
    ironExtractionFacility: [
        'Ironworks Global',
        'Deep Core Mining',
        'Red Earth Mines',
        'Steel Source Co',
        'Iron Ridge Corp',
        'Magnetite Mining Inc',
        'Ferrum Extraction Ltd',
        'Highland Iron Co',
        'Ore Masters Corp',
        'Taconite Mining Inc',
    ],
    coalPowerPlant: [
        'PowerGen Corp',
        'National Energy Ltd',
        'Continental Power Inc',
        'Grid Masters Corp',
        'Atlas Energy Group',
        'Volt Systems Ltd',
        'MegaWatt Corp',
        'Ampere Power Co',
        'Kilowatt Energy Inc',
        'ThermalPower Ltd',
    ],
    ironSmelter: [
        'Atlas Steel Works',
        'Meridian Steel Corp',
        'Nova Metals Group',
        'Forge Masters Inc',
        'Titan Steel Ltd',
        'Vulcan Metals Corp',
        'Ironclad Industries',
        'Red Forge Co',
        'Steel Dynamics Ltd',
        'Molten Steel Corp',
        'Crucible Metals Inc',
        'Alloy Masters Ltd',
    ],
    copperSmelter: [
        'World Copper Smelting',
        'Pacific Metals Corp',
        'Copper Dynamics Ltd',
        'Electro Metals Inc',
        'Conductive Corp',
        'Cathode Masters Ltd',
        'Refining Ventures',
        'Bronze Age Metals',
        'Copper Ridge Corp',
        'AlloyCraft Inc',
    ],
    oilRefinery: [
        'Horizon Refinery Corp',
        'Global Petrochemicals',
        'Coastal Refining Ltd',
        'Inland Refinery Co',
        'Continental Petrochem',
        'NorthWest Refining',
        'Gulf Coast Refineries',
        'Pacific Derivatives Corp',
        'Midland Refinery Group',
        'TarSands Processing',
        'HydroCarbon Corp',
        'Distillation Masters Ltd',
    ],
    sawmill: [
        'Global Sawmills Corp',
        'Timber Products Co',
        'Pacific Milling Inc',
        'Hardwood Processing Ltd',
        'Lumber Masters Corp',
        'Northern Mills Ltd',
        'Forest Products Inc',
        'Cedar Milling Co',
        'Pine Ridge Sawmill',
        'Boreal Processing Ltd',
        'Timberline Corp',
        'Woodland Milling Inc',
    ],
    cementPlant: [
        'Cement Giant Corp',
        'Continental Cement',
        'Urban Concrete Inc',
        'Grey Stone Corp',
        'Portland Cement Ltd',
        'Clinker Corp',
        'Building Stone Inc',
        'Pacific Cement Co',
        'Alpine Cement Ltd',
        'MegaMix Corp',
        'Foundation Materials Inc',
        'Bridge Cement Ltd',
    ],
    glassFactory: [
        'Glass World Ltd',
        'Crystal Dynamics Corp',
        'Clear Vision Glass',
        'Silicon Glass Inc',
        'Glazing Solutions Corp',
        'Optical Glass Ltd',
        'Continental Glass Corp',
        'Palace Glass Inc',
        'ArcticGlass Ltd',
        'Flint Glass Corp',
    ],
    pesticidePlant: ['GreenChem Ltd', 'CropGuard Corp', 'BioShield Chemicals', 'Field Protect Inc', 'AgriDefense Ltd'],
    paperMill: [
        'Paper World Inc',
        'Northern Paper Mills',
        'Pacific Pulp Corp',
        'Newsprint Dynamics',
        'Cellulose Masters Ltd',
    ],
    textileMill: [
        'Global Textiles Inc',
        'FiberCraft Corp',
        'Woven World Ltd',
        'Continental Fabric Corp',
        'Loom Masters Inc',
        'Thread & Fiber Co',
        'Pacific Weaving Corp',
        'Spinning Technologies Ltd',
        'Mill Stream Corp',
        'Fiber Dynamics Inc',
        'Eastern Textiles Ltd',
        'Yarn Masters Corp',
    ],
    concretePlant: [
        'Concrete Giant Corp',
        'Urban Materials Inc',
        'Stone Age Building',
        'MixMaster Corp',
        'Aggregate Solutions Ltd',
        'Foundation Corp',
        'Structural Mix Inc',
        'Precast Dynamics',
        'ReadyMix Co',
        'ConcreteTech Ltd',
        'Block & Slab Corp',
        'Paving Masters Inc',
    ],
    foodProcessingPlant: [
        'World Foods Corp',
        'Continental Food Inc',
        'Pacific Provisions Ltd',
        'Harvest Processing Corp',
        'FoodTech Inc',
        'Nourish Corp',
        'Global Provisions Ltd',
        'Ready Meals Corp',
        'Processed Foods Inc',
        'Canned Goods Corp',
        'FoodChain Ltd',
        'Nutrition Masters Inc',
    ],
    beveragePlant: [
        'Beverage Planet Inc',
        'Freshdrink Co',
        'ThirstQuench Corp',
        'LiquidRefresh Ltd',
        'Bottle Factory Corp',
        'DrinkWorks Inc',
        'H2O Plus Corp',
        'Sunrise Beverages',
        'Pacific Drinks Ltd',
        'Continental Beverages Corp',
    ],
    pharmaceuticalPlant: [
        'PharmaGlobal Corp',
        'MedLife Corp',
        'BioSynth Inc',
        'CureAll Pharmaceuticals',
        'Remedy Corp',
        'HealTech Ltd',
        'Compound Dynamics',
        'Generic Meds Inc',
        'Research Pharma Corp',
        'Vital Drugs Ltd',
    ],
    clothingFactory: [
        'Fashion World Ltd',
        'Garment Masters Corp',
        'Global Apparel Inc',
        'ThreadWorks Ltd',
        'StitchRight Corp',
        'ClothCraft Inc',
        'WearTech Corp',
        'StyleMakers Ltd',
        'Fabric Arts Corp',
        'Couture Industries Inc',
        'Ready-to-Wear Corp',
        'Drape & Stitch Ltd',
    ],
    furnitureFactory: [
        'Home Furnishings Corp',
        'Woodcraft International',
        'LivingSpace Corp',
        'HomeWorks Ltd',
        'Comfort Furniture Inc',
        'Nordic Design Corp',
        'Wooden Dreams Ltd',
        'Casa Furniture Inc',
        'GoodHome Corp',
        'Modern Furnishings Ltd',
        'Classic Wood Corp',
        'Interior Masters Inc',
    ],
    electronicComponentFactory: [
        'Silicon Dynamics Corp',
        'Global Electronics Inc',
        'Circuit World Ltd',
        'Component Masters Corp',
        'PCB Dynamics Inc',
        'Micro Elements Ltd',
        'TechParts Corp',
        'Board Masters Inc',
        'ChipWorks Ltd',
        'ElectroBase Corp',
    ],
    consumerElectronicsFactory: [
        'TechVision Corp',
        'Gadget World Inc',
        'Device Planet Ltd',
        'SmartTech Corp',
        'DigitalEdge Inc',
        'Consumer Electronics Ltd',
        'NextGen Devices Corp',
        'Pixel Perfect Inc',
        'ElectoHome Ltd',
        'TechLife Corp',
        'Digital Masters Inc',
        'SmartHome Corp',
    ],
    machineryFactory: [
        'Mech Industries Ltd',
        'Heavy Works International',
        'Precision Engineering Co',
        'Iron Horse Machinery',
        'Gear Works Corp',
    ],
    vehicleFactory: [
        'Automotion Corp',
        'DriveTech Motors',
        'Precision Parts Co',
        'WheelWorks Corp',
        'Motor Masters Ltd',
    ],
    intensiveFarmFacility: [
        'AgroTech Global',
        'Precision Farming Inc',
        'Yield Max Corp',
        'GrowSmart Ltd',
        'Crop Science Corp',
        'AgroVentures Inc',
        'Cultivar Corp',
        'FarmTech Ltd',
        'PrecisionCrop Inc',
        'HighYield Farms',
        'CropDynamics Corp',
        'Agronomics Ltd',
    ],
    packagingPlant: [
        'PackGlobal Corp',
        'Wrap World Inc',
        'BoxMakers Ltd',
        'Container Corp',
        'PackArt Inc',
        'ShipRight Corp',
        'Pack Dynamics Ltd',
        'BulkPack Corp',
        'Seal Masters Inc',
        'WrapTech Corp',
        'PackSolutions Ltd',
        'Crate & Box Corp',
    ],
    administrativeCenter: [
        'Global Admin Services',
        'Civic Solutions Corp',
        'Metro Admin Group',
        'BackOffice Corp',
        'AdminWorld Inc',
        'Corporate Services Ltd',
        'BizAdmin Corp',
        'Central Office Inc',
        'OfficeTech Corp',
        'AdminPro Ltd',
        'Enterprise Services Corp',
        'SupportHub Inc',
    ],
    logisticsHub: [
        'Swift Logistics Corp',
        'Global Freight Ltd',
        'Nexus Distribution Inc',
        'MoveIt Corp',
        'FlowChain Ltd',
        'ShipFast Corp',
        'RouteMax Inc',
        'Cargo Masters Ltd',
        'DeliverAll Corp',
        'FreightWorks Inc',
        'TransitHub Ltd',
        'LogiFlow Corp',
    ],
    constructionService: [
        'BuildRight Services',
        'Urban Construct Co',
        'Global Builders Corp',
        'Foundation Works Inc',
        'ErectAll Ltd',
        'SkyHigh Construction',
        'GroundWork Corp',
        'MegaBuild Inc',
        'Construct Masters Ltd',
        'TowerBuilders Corp',
        'BlueCollar Services Inc',
        'EliteBuild Corp',
    ],
    groceryChain: [
        'FreshMart Chain',
        'World Grocery Corp',
        'Daily Basket Inc',
        'Metro Grocers Ltd',
        'SuperFresh Corp',
        'GrocerWorld Inc',
        'The Food Depot',
        'FoodFirst Corp',
        'Pantry Masters Ltd',
        'FreshChoice Inc',
        'BigBasket Corp',
        'GrocerPlus Ltd',
    ],
    retailChain: [
        'OmniRetail Corp',
        'Global Shops Ltd',
        'Prime Retail Chain',
        'MegaMart Inc',
        'ShopWorld Corp',
        'RetailFirst Ltd',
        'StoreChain Corp',
        'OpenMart Inc',
        'ValueShop Corp',
        'BuyMore Ltd',
        'ShopSmart Corp',
        'BargainWorld Inc',
    ],
    hospital: [
        'HealthNet Corp',
        'Global Care Ltd',
        'Metro Health Group',
        'CureAll Clinics',
        'WellBeing Corp',
        'MedCenter Inc',
        'LifeHealth Corp',
        'CareFirst Ltd',
        'Vitality Health Corp',
        'HealAll Inc',
        'MediGroup Ltd',
        'WellnessFirst Corp',
    ],
    siliconWaferFactory: [
        'WaferTech Corp',
        'Global Wafers Inc',
        'Silicon Masters Ltd',
        'PureSilicon Corp',
        'Wafer Dynamics Inc',
        'CrystalSilicon Ltd',
        'SemiConductor Corp',
        'Wafer Works Inc',
        'SiliconEdge Ltd',
        'ChipStart Corp',
    ],
};
