// THIS FILE IS AUTO-GENERATED by tools/facility-growth-model/computeTargets.ts
// Run: npx tsx tools/facility-growth-model/computeTargets.ts

export const FACILITY_SCALE_PER_BILLION: Record<string, number> = {
    administrativeCenter: 48247.25,
    agriculturalFacility: 62057.125,
    beveragePlant: 41563.25,
    cementPlant: 215040,
    clothingFactory: 34636,
    coalMine: 16609.625,
    concretePlant: 268800,
    constructionFacility: 268800,
    copperMine: 12497.875,
    copperSmelter: 20829.875,
    cottonFarm: 40890.625,
    educationCenter: 6194.375,
    electronicsFactory: 52074.625,
    foodProcessor: 77931.125,
    furnitureFactory: 56079.125,
    glassFactory: 33626.5,
    groceryChain: 207816.125,
    hospital: 129315.5,
    ironMine: 71722.625,
    ironSmelter: 191260.5,
    itDevicesFactory: 104149.375,
    limestoneQuarry: 47491.5,
    loggingCamp: 43901.25,
    logisticsHub: 159353.875,
    machineryFactory: 19163.25,
    maintenanceFacility: 0.125,
    oilRefinery: 251311.875,
    oilWell: 251311.875,
    packagingPlant: 5974.75,
    paperMill: 2455.75,
    pesticidePlant: 20685.75,
    pharmaPlant: 64657.75,
    retailChain: 207816.125,
    sandMine: 78690.625,
    sawmill: 28039.625,
    siliconWaferFactory: 26037.375,
    stoneQuarry: 107520,
    textileMill: 34075.625,
    vehicleFactory: 15176.5,
    waterFacility: 52078.625,
};

export const CONSTRUCTION_DEMAND_PER_TICK = 512000000;

export const TARGET_SCALE_PER_AGENT = 150000;
