// THIS FILE IS AUTO-GENERATED by tools/facility-growth-model/computeTargets.ts
// Run: npx tsx tools/facility-growth-model/computeTargets.ts

export const FACILITY_SCALE_PER_BILLION: Record<string, number> = {
    administrativeCenter: 98624.625,
    agriculturalFacility: 62057.125,
    beveragePlant: 41563.25,
    cementPlant: 215040,
    clothingFactory: 34636,
    coalMine: 16624,
    concretePlant: 268800,
    constructionFacility: 268800,
    copperMine: 12528.125,
    copperSmelter: 20880.25,
    cottonFarm: 41012.375,
    educationCenter: 6194.375,
    electronicsFactory: 52200.625,
    foodProcessor: 77931.125,
    furnitureFactory: 57086.75,
    glassFactory: 33702.375,
    groceryChain: 207816.125,
    hospital: 129315.5,
    ironMine: 71799.625,
    ironSmelter: 191465.625,
    itDevicesFactory: 104401.25,
    limestoneQuarry: 47501.625,
    loggingCamp: 48355.25,
    logisticsHub: 159489.375,
    machineryFactory: 19165.875,
    maintenanceFacility: 0.125,
    oilRefinery: 251387.75,
    oilWell: 251387.75,
    packagingPlant: 5974.75,
    paperMill: 7387,
    pesticidePlant: 20685.75,
    pharmaPlant: 64657.75,
    retailChain: 207816.125,
    sandMine: 78791.5,
    sawmill: 28543.375,
    siliconWaferFactory: 26100.25,
    stoneQuarry: 107520,
    textileMill: 34177,
    vehicleFactory: 15189.5,
    waterFacility: 52406.75,
};

export const CONSTRUCTION_DEMAND_PER_TICK = 512000000;

export const TARGET_SCALE_PER_AGENT = 150000;
