// THIS FILE IS AUTO-GENERATED by tools/facility-growth-model/computeTargets.ts
// Run: npx tsx tools/facility-growth-model/computeTargets.ts

export const FACILITY_SCALE_PER_BILLION: Record<string, number> = {
    administrativeCenter: 95959.375,
    agriculturalFacility: 62057.125,
    beveragePlant: 41563.25,
    cementPlant: 215040,
    clothingFactory: 34636,
    coalMine: 16623,
    concretePlant: 268800,
    constructionFacility: 268800,
    copperMine: 12526.5,
    copperSmelter: 20877.625,
    cottonFarm: 41005.375,
    educationCenter: 6194.375,
    electronicsFactory: 52194,
    foodProcessor: 77931.125,
    furnitureFactory: 57033.375,
    glassFactory: 33698.125,
    groceryChain: 207816.125,
    hospital: 129315.5,
    ironMine: 71794.625,
    ironSmelter: 191452.25,
    itDevicesFactory: 104387.875,
    limestoneQuarry: 47501.125,
    loggingCamp: 44616.875,
    logisticsHub: 159387,
    machineryFactory: 19164,
    maintenanceFacility: 0.125,
    oilRefinery: 251383.625,
    oilWell: 251383.625,
    packagingPlant: 5974.75,
    paperMill: 2455.75,
    pesticidePlant: 20685.75,
    pharmaPlant: 64657.75,
    retailChain: 207816.125,
    sandMine: 78786,
    sawmill: 28516.75,
    siliconWaferFactory: 26097,
    stoneQuarry: 107520,
    textileMill: 34171.125,
    vehicleFactory: 15179.75,
    waterFacility: 52097.375,
};

export const CONSTRUCTION_DEMAND_PER_TICK = 512000000;

export const TARGET_SCALE_PER_AGENT = 150000;
