import type { Resource, TradableResourceProcessLevel } from './claims';
import {
    beverageResourceType,
    cementResourceType,
    chemicalResourceType,
    clothingResourceType,
    coalResourceType,
    concreteResourceType,
    consumerElectronicsResourceType,
    copperOreResourceType,
    copperResourceType,
    cottonResourceType,
    crudeOilResourceType,
    electronicsResourceType,
    fabricResourceType,
    fuelResourceType,
    furnitureResourceType,
    glassResourceType,
    ironOreResourceType,
    limestoneResourceType,
    logsResourceType,
    lumberResourceType,
    machineryResourceType,
    packagingResourceType,
    paperResourceType,
    pesticideResourceType,
    pharmaceuticalResourceType,
    plasticResourceType,
    processedFoodResourceType,
    produceResourceType,
    sandResourceType,
    siliconWaferResourceType,
    steelResourceType,
    stoneResourceType,
    vehicleResourceType,
    waterResourceType,
} from './resources';
import {
    administrativeServiceResourceType,
    constructionServiceResourceType,
    educationServiceResourceType,
    groceryServiceResourceType,
    healthcareServiceResourceType,
    logisticsServiceResourceType,
    maintenanceServiceResourceType,
    retailServiceResourceType,
} from './services';

export const TRADABLE_RESOURCES: Resource[] = [
    ironOreResourceType,
    waterResourceType,
    produceResourceType,
    coalResourceType,
    crudeOilResourceType,
    logsResourceType,
    stoneResourceType,
    copperOreResourceType,
    sandResourceType,
    limestoneResourceType,
    steelResourceType,
    copperResourceType,
    plasticResourceType,
    chemicalResourceType,
    fuelResourceType,
    lumberResourceType,
    cementResourceType,
    concreteResourceType,
    glassResourceType,
    pesticideResourceType,
    pharmaceuticalResourceType,
    processedFoodResourceType,
    beverageResourceType,
    paperResourceType,
    cottonResourceType,
    fabricResourceType,
    clothingResourceType,
    furnitureResourceType,
    siliconWaferResourceType,
    electronicsResourceType,
    consumerElectronicsResourceType,
    machineryResourceType,
    vehicleResourceType,
    packagingResourceType,
    administrativeServiceResourceType,
    logisticsServiceResourceType,
    constructionServiceResourceType,
    groceryServiceResourceType,
    retailServiceResourceType,
    healthcareServiceResourceType,
    educationServiceResourceType,
    maintenanceServiceResourceType,
] as const;

export const RESOURCES_BY_NAME: ReadonlyMap<string, Resource> = new Map(
    TRADABLE_RESOURCES.map((resource) => [resource.name, resource] as const),
);

export const getProductForm = (resourceName: string): Resource['form'] | undefined => {
    return RESOURCES_BY_NAME.get(resourceName)?.form;
};

export const RESOURCE_LEVELS: TradableResourceProcessLevel[] = ['raw', 'refined', 'manufactured', 'services'];

export const RESOURCE_LEVEL_LABELS: Record<TradableResourceProcessLevel, string> = {
    raw: 'Raw',
    refined: 'Refined',
    manufactured: 'Manufactured',
    services: 'Services',
};
