import type { Resource, ResourceProcessLevel } from './planet';
import {
    ironOreResourceType,
    waterResourceType,
    agriculturalProductResourceType,
    coalResourceType,
    crudeOilResourceType,
    naturalGasResourceType,
    logsResourceType,
    stoneResourceType,
    bauxiteResourceType,
    copperOreResourceType,
    rareEarthOreResourceType,
    sandResourceType,
    limestoneResourceType,
    clayResourceType,
    steelResourceType,
    aluminumResourceType,
    copperResourceType,
    plasticResourceType,
    chemicalResourceType,
    gasolineResourceType,
    dieselResourceType,
    jetFuelResourceType,
    lubricantResourceType,
    asphaltResourceType,
    lumberResourceType,
    cementResourceType,
    concreteResourceType,
    brickResourceType,
    glassResourceType,
    phosphateRockResourceType,
    potashResourceType,
    fertilizerResourceType,
    pesticideResourceType,
    pharmaceuticalResourceType,
    processedFoodResourceType,
    beverageResourceType,
    paperResourceType,
    cottonResourceType,
    fabricResourceType,
    clothingResourceType,
    furnitureResourceType,
    electronicComponentResourceType,
    consumerElectronicsResourceType,
    machineryResourceType,
    vehicleResourceType,
} from './resources';

export const ALL_RESOURCES: Resource[] = [
    ironOreResourceType,
    waterResourceType,
    agriculturalProductResourceType,
    coalResourceType,
    crudeOilResourceType,
    naturalGasResourceType,
    logsResourceType,
    stoneResourceType,
    bauxiteResourceType,
    copperOreResourceType,
    rareEarthOreResourceType,
    sandResourceType,
    limestoneResourceType,
    clayResourceType,
    steelResourceType,
    aluminumResourceType,
    copperResourceType,
    plasticResourceType,
    chemicalResourceType,
    gasolineResourceType,
    dieselResourceType,
    jetFuelResourceType,
    lubricantResourceType,
    asphaltResourceType,
    lumberResourceType,
    cementResourceType,
    concreteResourceType,
    brickResourceType,
    glassResourceType,
    phosphateRockResourceType,
    potashResourceType,
    fertilizerResourceType,
    pesticideResourceType,
    pharmaceuticalResourceType,
    processedFoodResourceType,
    beverageResourceType,
    paperResourceType,
    cottonResourceType,
    fabricResourceType,
    clothingResourceType,
    furnitureResourceType,
    electronicComponentResourceType,
    consumerElectronicsResourceType,
    machineryResourceType,
    vehicleResourceType,
];

export const RESOURCE_LEVELS: ResourceProcessLevel[] = ['raw', 'refined', 'manufactured', 'consumerGood'];

export const RESOURCE_LEVEL_LABELS: Record<ResourceProcessLevel, string> = {
    source: 'Source',
    raw: 'Raw',
    refined: 'Refined',
    manufactured: 'Manufactured',
    consumerGood: 'Consumer Goods',
};

export const resourcesByLevel: Record<ResourceProcessLevel, Resource[]> = {
    source: [],
    raw: ALL_RESOURCES.filter((r) => r.level === 'raw'),
    refined: ALL_RESOURCES.filter((r) => r.level === 'refined'),
    manufactured: ALL_RESOURCES.filter((r) => r.level === 'manufactured'),
    consumerGood: ALL_RESOURCES.filter((r) => r.level === 'consumerGood'),
};
