import type { Resource, ResourceProcessLevel } from './planet';
import {
    agriculturalProductResourceType,
    aluminumResourceType,
    bauxiteResourceType,
    beverageResourceType,
    brickResourceType,
    cementResourceType,
    chemicalResourceType,
    clayResourceType,
    clothingResourceType,
    coalResourceType,
    concreteResourceType,
    consumerElectronicsResourceType,
    copperOreResourceType,
    copperResourceType,
    cottonResourceType,
    crudeOilResourceType,
    electronicComponentResourceType,
    fabricResourceType,
    fertilizerResourceType,
    fuelResourceType,
    furnitureResourceType,
    glassResourceType,
    ironOreResourceType,
    limestoneResourceType,
    logsResourceType,
    lubricantResourceType,
    lumberResourceType,
    machineryResourceType,
    naturalGasResourceType,
    paperResourceType,
    pesticideResourceType,
    pharmaceuticalResourceType,
    phosphateRockResourceType,
    plasticResourceType,
    potashResourceType,
    processedFoodResourceType,
    rareEarthOreResourceType,
    sandResourceType,
    steelResourceType,
    stoneResourceType,
    vehicleResourceType,
    waterResourceType,
    packagingResourceType,
} from './resources';
import {
    administrativeServiceResourceType,
    constructionServiceResourceType,
    groceryServiceResourceType,
    healthcareServiceResourceType,
    logisticsServiceResourceType,
    retailServiceResourceType,
} from './services';

export const ALL_RESOURCES: Resource[] = [
    ironOreResourceType,
    waterResourceType,
    agriculturalProductResourceType,
    coalResourceType,
    crudeOilResourceType,
    naturalGasResourceType,
    logsResourceType,
    stoneResourceType,
    bauxiteResourceType,
    copperOreResourceType,
    rareEarthOreResourceType,
    sandResourceType,
    limestoneResourceType,
    clayResourceType,
    steelResourceType,
    aluminumResourceType,
    copperResourceType,
    plasticResourceType,
    chemicalResourceType,
    fuelResourceType,
    lubricantResourceType,
    lumberResourceType,
    cementResourceType,
    concreteResourceType,
    brickResourceType,
    glassResourceType,
    phosphateRockResourceType,
    potashResourceType,
    fertilizerResourceType,
    pesticideResourceType,
    pharmaceuticalResourceType,
    processedFoodResourceType,
    beverageResourceType,
    paperResourceType,
    cottonResourceType,
    fabricResourceType,
    clothingResourceType,
    furnitureResourceType,
    electronicComponentResourceType,
    consumerElectronicsResourceType,
    machineryResourceType,
    vehicleResourceType,
    packagingResourceType,
    administrativeServiceResourceType,
    logisticsServiceResourceType,
    constructionServiceResourceType,
    groceryServiceResourceType,
    retailServiceResourceType,
    healthcareServiceResourceType,
] as const;

export const RESOURCE_LEVELS: ResourceProcessLevel[] = ['raw', 'refined', 'manufactured', 'services'];

export const RESOURCE_LEVEL_LABELS: Record<ResourceProcessLevel, string> = {
    source: 'Source',
    raw: 'Raw',
    refined: 'Refined',
    manufactured: 'Manufactured',
    services: 'Services',
};

export const resourcesByLevel: Record<ResourceProcessLevel, Resource[]> = {
    source: [],
    raw: ALL_RESOURCES.filter((r) => r.level === 'raw'),
    refined: ALL_RESOURCES.filter((r) => r.level === 'refined'),
    manufactured: ALL_RESOURCES.filter((r) => r.level === 'manufactured'),
    services: ALL_RESOURCES.filter((r) => r.level === 'services'),
};
