export const MAX_SCALE_EXPAND_FRACTION = 0.025;
export const EXPANSION_WORKING_CAPITAL_TICKS = 20;
export const HR_EXPANSION_MIN_PRODUCTIVITY_MULTIPLIER = 0.9;
export const STORAGE_STARVATION_EXPANSION_MAX = 0.05;

export const MIN_SCALE_FRACTION = 0.25;
export const SOFT_FLOOR_RELAXATION = 0.5;

export const PID_KP = 0.01;

export const PID_KI = 0.0001;

export const PID_KD = 0.01;
export const PID_IMAX = 0.0001;

export const STORAGE_TARGET_MONTHS = 3;
export const STORAGE_CAPACITY_MONTHS = 6;

export const STORAGE_ERROR_ZOOM_MONTHS = 1;
export const STORAGE_TREND_HORIZON_MONTHS = 1;

export const PID_OUT_MAX_UP = 0.02;
export const PID_OUT_MAX_DOWN = 0.01;
export const PID_D_ALPHA = 0.3;
export const SIGNAL_EMA_ALPHA = 0.3;

export const EXPANSION_INTEGRAL_THRESHOLD = 30;
export const EXPANSION_INTEGRAL_MAX = 180;
export const EXPANSION_INTEGRAL_DECAY = 0.05;
export const EXPANSION_PRICE_INFLATION_THRESHOLD = 3.0;
export const EXPANSION_WORKER_RESERVE_MARGIN = 0.3;

export const DYNAMIC_EXPANSION_CAP_FRACTION = 0.1;
export const EXPANSION_AT_CAPACITY_FRACTION = 0.98;

export const MAX_SCALE_CONTRACT_FRACTION = 0.01;
export const CONTRACTION_AT_SCALE_FRACTION = 0.5;
export const CONTRACTION_INTEGRAL_THRESHOLD = 15;
export const CONTRACTION_INTEGRAL_MAX = 180;
export const CONTRACTION_INTEGRAL_DECAY = 0.05;

export const STORAGE_EXPANSION_RATE = 0.2;
export const STORAGE_CONTRACTION_RATE = 0.1;
